@echo off
setlocal EnableExtensions EnableDelayedExpansion
title Overwatch 2 Server Picker - uninstall

rem Removes the Start Menu entry and the installed files.
rem
rem Firewall rules are dealt with FIRST, and that ordering is the point: deleting the app
rem while blocks are active would leave Overwatch permanently restricted to whatever was
rem selected, with nothing left on the machine that knows how to undo it.

set "DEST=%LOCALAPPDATA%\Programs\Ow2ServerPicker"
rem If this script sits next to the app, uninstall that copy - it may have been installed
rem somewhere else by hand.
if exist "%~dp0Ow2ServerPicker.exe" set "DEST=%~dp0"
if "%DEST:~-1%"=="\" set "DEST=%DEST:~0,-1%"

set "LNK=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Overwatch 2 Server Picker.lnk"
set "HELPER=%TEMP%\ow2sp-uninstall-helper.ps1"
set "KILLRULES=0"

echo.
echo   Uninstalling Overwatch 2 Server Picker
echo   from : %DEST%
echo.

rem --- are any rules still active? ----------------------------------------------
set "RULES=0"
for /f %%c in ('powershell -NoProfile -Command ^
  "@(Get-NetFirewallRule -DisplayName 'OW2ServerPicker*' -ErrorAction SilentlyContinue).Count" 2^>nul') do set "RULES=%%c"

if "%RULES%"=="0" (
    echo   No firewall rules from this app are active.
) else (
    echo   %RULES% firewall rule^(s^) from this app are still active.
    echo   Leaving them in place keeps Overwatch restricted with nothing left to undo it.
    echo.
    choice /c YN /n /m "   Remove them now (requires administrator)? [Y/N] "
    if errorlevel 2 (
        echo.
        echo   Left in place. To remove them later, in an elevated PowerShell:
        echo     Get-NetFirewallRule -DisplayName 'OW2ServerPicker*' ^| Remove-NetFirewallRule
    ) else (
        set "KILLRULES=1"
    )
)

rem --- close the app ------------------------------------------------------------
rem A plain taskkill fails against an elevated instance with "Access is denied", which
rem previously left the exe locked and the folder undeletable.
taskkill /f /im Ow2ServerPicker.exe >nul 2>&1
set "RUNNING=0"
for /f %%c in ('powershell -NoProfile -Command ^
  "@(Get-Process Ow2ServerPicker -ErrorAction SilentlyContinue).Count" 2^>nul') do set "RUNNING=%%c"

rem --- one elevated pass for whatever still needs it -----------------------------
if "%KILLRULES%%RUNNING%"=="00" goto :noelevate

> "%HELPER%" echo # generated by uninstall.cmd
if "%KILLRULES%"=="1" (
    >> "%HELPER%" echo Get-NetFirewallRule -DisplayName 'OW2ServerPicker*' -ErrorAction SilentlyContinue ^| Remove-NetFirewallRule
)
>> "%HELPER%" echo Get-Process Ow2ServerPicker -ErrorAction SilentlyContinue ^| Stop-Process -Force

echo.
echo   Requesting administrator rights...
powershell -NoProfile -Command ^
  "Start-Process powershell -Verb RunAs -Wait -ArgumentList '-NoProfile','-ExecutionPolicy','Bypass','-File','%HELPER%'" >nul 2>&1
del "%HELPER%" >nul 2>&1

:noelevate
rem --- report what actually happened, do not assume ------------------------------
set "LEFT=0"
for /f %%c in ('powershell -NoProfile -Command ^
  "@(Get-NetFirewallRule -DisplayName 'OW2ServerPicker*' -ErrorAction SilentlyContinue).Count" 2^>nul') do set "LEFT=%%c"
if "%KILLRULES%"=="1" (
    if "!LEFT!"=="0" (echo   Firewall rules removed.) else (echo   WARNING: !LEFT! rule^(s^) could not be removed.)
)

echo.
if exist "%LNK%" (
    del /f /q "%LNK%" >nul 2>&1
    if exist "%LNK%" (echo   WARNING: could not remove the Start Menu entry.) else (echo   Start Menu entry removed.)
) else (
    echo   No Start Menu entry found.
)

if not exist "%DEST%\Ow2ServerPicker.exe" (
    echo   Nothing installed at %DEST%
    goto :done
)

rem Delete what we can verify now; the folder still holds this script.
del /f /q "%DEST%\Ow2ServerPicker.exe" >nul 2>&1
del /f /q "%DEST%\servers.json" "%DEST%\servers.json.previous" >nul 2>&1
if exist "%DEST%\tools" rd /s /q "%DEST%\tools" >nul 2>&1

if exist "%DEST%\Ow2ServerPicker.exe" (
    echo.
    echo   WARNING: Ow2ServerPicker.exe is still locked - it may still be running.
    echo   Close it and run this again, or delete %DEST% by hand.
    goto :done
)
echo   Application files removed from %DEST%

:done
echo.
echo   Done.
echo.
pause

rem The folder holds this script, so the final delete has to outlive it. ping is used
rem as the delay because timeout fails outright when stdin is redirected.
start "" /b cmd /c "ping -n 3 127.0.0.1 >nul & rd /s /q ""%DEST%"" >nul 2>&1"
exit /b 0
