# Generates src/BuildInfo.generated.cs before every compile.
#
# The version is derived, never hand-edited, because a version someone has to remember to
# bump is a version that silently goes stale - and a stale version number is worse than none,
# since it actively asserts you are running something you are not.
#
#   patch  = commit count, so it increases on every commit
#   commit = short hash, with a trailing + when the working tree has uncommitted changes
#   built  = timestamp, which is what distinguishes two builds of the same commit
param(
    [string]$OutFile = (Join-Path (Split-Path $PSScriptRoot -Parent) 'src\BuildInfo.generated.cs')
)
$ErrorActionPreference = 'SilentlyContinue'

$major = 1
$minor = 0
$patch = 0
$commit = 'nogit'

# A downloaded source zip has no git history; the build must still work.
$count = git rev-list --count HEAD 2>$null
if ($LASTEXITCODE -eq 0 -and $count) {
    $patch = [int]$count
    $short = git rev-parse --short HEAD 2>$null
    if ($short) { $commit = $short.Trim() }
    $dirty = git status --porcelain 2>$null
    if ($dirty) { $commit = $commit + '+' }   # built from a modified tree
}

$version = "$major.$minor.$patch"
$built = (Get-Date).ToString('yyyy-MM-dd HH:mm')

$body = @"
// GENERATED by tools/gen-version.ps1 - do not edit, do not commit.
namespace Ow2ServerPicker
{
    internal static class BuildInfo
    {
        public const string Version = "$version";
        public const string Commit  = "$commit";
        public const string Built   = "$built";
    }
}
"@

New-Item -ItemType Directory -Path (Split-Path $OutFile) -Force | Out-Null

# Only rewrite when something actually changed, so an unchanged rebuild does not churn
# the file timestamp and force a needless recompile.
$existing = if (Test-Path $OutFile) { Get-Content $OutFile -Raw } else { '' }
$new = $body -replace "`r`n", "`n"
$old = $existing -replace "`r`n", "`n"
$oldNoTime = $old -replace 'Built   = "[^"]*"', ''
$newNoTime = $new -replace 'Built   = "[^"]*"', ''
if ($oldNoTime -ne $newNoTime -or -not (Test-Path $OutFile)) {
    Set-Content -Path $OutFile -Value $body -Encoding UTF8
}

Write-Host ("  version {0} ({1}) built {2}" -f $version, $commit, $built)
